### ISSUE TITLE
Positionable suddenly needs access to browsing history

### ISSUE THREAD

**Issue by ArjanKw** [andrewplummer/Positionable#14]
Hi Andrew,

A few days ago I received the following message in Chrome:

![image](https://user-images.githubusercontent.com/12813016/112300061-c00e1c80-8c98-11eb-8834-7eb5527baf13.png)

Why does a working plugin suddenly need access to private browsing history? Browsing history seems to be unreIated to the function of this extension. Furthermore, when I look into the manifest.json, I don't see that this permission is required. The version of the extension in Chrome is 2.1.1, while the manifest.json in Github is 2.1.0. So it seems like a 2.1.1 update is pushed for which the code isn't shown in Github.

I have used this extension in the past and would like to use it in the future if necessary. Is it possible to explain why this permission is needed and show the code in Github? It would also be good if the need for this permission is explained in the Chrome web store.

Thanks in advance,

Arjan

**Comment by andrewplummer** [comment]
You're right it shouldn't be required. I did some manifest updates recently that seem to have broke it.. can you check which manifest version your installed version is? The updates to v3 seem unstable so I've reverted to v2, but it's likely that the review is taking a while, so it might take a bit of time.

**Comment by ArjanKw** [comment]
Thanks for your reply. The manifest version that is installed is 2.1.1. 

I found the following in C:\Users\arjan\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Extensions\hcakmjkjjgaehnnflnelfngbhnppgnpp\2.1.1_0\manifest.json:

```
{
   "background": {
      "persistent": false,
      "scripts": [ "worker.js" ]
   },
   "browser_action": {
      "default_icon": "images/app/16.png",
      "default_title": "Positionable!"
   },
   "description": "An extension for visually manipulating elements in the browser.",
   "differential_fingerprint": "1.5d792442f02aa0c3a9 ... 4b5564c9b935ee0c8dff565",
   "icons": {
      "128": "images/app/128.png",
      "16": "images/app/16.png",
      "32": "images/app/32.png",
      "48": "images/app/48.png"
   },
   "key": "MIIBIjANBgkq ... k2tQyr8kLvydCCVmpYAWFQIDAQAB",
   "manifest_version": 2,
   "name": "Positionable!",
   "offline_enabled": true,
   "permissions": [ "activeTab", "storage", "tabs" ],
   "short_name": "Positionable",
   "update_url": "https://clients2.google.com/service/update2/crx",
   "version": "2.1.1",
   "web_accessible_resources": [ "*.html", "*.css", "images/*" ]
}
```

I would have expected the "history" permission to be in there as well as Brave is still stating that it needs that permission to be enabled again:

![image](https://user-images.githubusercontent.com/12813016/112391209-dac3ae00-8cf7-11eb-9ed0-7bff7ef2c05c.png)

Reinstalling doesn't do the trick and the same happens both in Brave and Chrome.

If you need more information please let me know. Thanks in advance!

**Comment by andrewplummer** [comment]
ok I've filed a bug report and seem to have gotten an answer so trying out manifest v3 again for a new version 2.1.2 ... let me know if you can install this one once it's out... thanks!

**Comment by ArjanKw** [comment]
Thanks Andrew, you've solved it! The message disappeared. I also reinstalled the extension afterwards and it doesn't ask for the history permission anymore.

**Comment by andrewplummer** [comment]
great! I'm slightly surprised because the publishing was so fast but at any rate that seems to have worked and it's manifest v3 now so I think this should be good now... thanks!

**Comment by ArjanKw** [comment]
I was also surprised with the speed. Maybe they sped up the process for a small change. Anyway it updated from 2.1.1 to 2.1.2 and the message disappeared:

![image](https://user-images.githubusercontent.com/12813016/112604352-51ef6400-8e16-11eb-83ed-2e7e43a2b424.png)

![image](https://user-images.githubusercontent.com/12813016/112604705-bf9b9000-8e16-11eb-9669-5558da0a7d08.png)
(translated: The extension doesn't require special permissions).

**Comment by andrewplummer** [comment]
excellent.. thanks for helping solve this one
