### ISSUE TITLE
Extremely difficult to pick up the DOM element you need

### ISSUE THREAD

**Issue by intellix** [andrewplummer/Positionable#5]
Found Positionable through google after thinking... how is this still not possible?! I have a couple of elements I'd like to move into position.

With the overlay for dragging it seems very difficult to actually select the item you want to. I've got a couple of elements inside a modal and every time I click on them it just selects the modal. 

Is it possible to just pick items directly from the developer tools Elements tab?

**Comment by andrewplummer** [comment]
That's actually a great idea! I'll see what I can do.

**Comment by andrewplummer** [comment]
Still planning to have a look at this but for now you can (should) just exclude the modal using the class exclusion feature in settings. Sorry should have mentioned this earlier.

**Comment by andrewplummer** [comment]
Also, can you help out with the issue you're having? I don't have a problem selecting nested elements... is it just that the elements inside the modal are too small?

**Comment by andrewplummer** [comment]
Ok, there's a new version out... it has an element "selector" so you can choose elements, even ones you can't see (if they're off-screen or hidden behind other elements, etc.)
