### ISSUE TITLE
Add support for css transform: translate3d(...)

### ISSUE THREAD

**Issue by brussee** [andrewplummer/Positionable#6]
Please add support for the example below:
```
element.style {
    position: absolute;
    top: 0px;
    left: 0px;
    z-index: 10000;
    transition: all 0.3s;
    transform: translate3d(30px, 401px, 0px);
}
```
Elements like this are created by [react-visualizer](https://github.com/spredfast/react-transform-render-visualizer), but some are completely overlapping, which is why I would like to use Positionable to move them.

**Comment by andrewplummer** [comment]
Will have a look at this, thanks!

**Comment by andrewplummer** [comment]
Just released a new version... it should work nicely now!
